### PR TITLE
Match English to Latin in Communion Antiphon

### PR DESCRIPTION
**Pull request by dokeefe9999**

### CODE REVIEW

**Comment by ajmalton** [comment]
Strangely: this commit appears in my github app to consist of two files which both had every line replaced by the same line again.

What _really_ happened?

**Comment by dokeefe9999** [comment]
All I did was replace "him" with "Christ the Lord" in the Communion antiphon.

I have a new laptop. I wonder if I set up Git line feed/return line endings incorrectly?  I believe I set them up for no conversions either way.
________________________________

**Comment by ajmalton** [comment]
That seems very possible. Also I am not convinced your master is properly based on our upstream.

Your file C6bp.txt does not exist in master. Your file C6b.txt contains a whole Commune: but in master it's just a one line reference to C6.

Can you clean up your history and reissue the PR?

**Comment by dokeefe9999** [comment]
Will do. Thanks.
________________________________

**Comment by ajmalton** [comment]
But looking more carefully, perhaps, I see that you made that one change, which indeed make the English clause a correct translation.

However, it does still appear in git that the whole of both files have been changed, with most lines apparently identical before and after. Obviously that's not desirable in general, even if here it might not matter much.

Can you see what's causing this and fix it? (Does the PR look like that to you?)

**Comment by dokeefe9999** [comment]
I'm reinstalling Git on my machine, this time converting Unix line feeds to Windows style and then back again. I'll also check on the existence of these files once I reclone. Maybe I cloned from the wrong source originally.
________________________________

**Comment by dokeefe9999** [comment]
Funny, I just recloned and C6bp.txt is still in there.  When I look at the github site I also see it.

[cid:8706bd0a-4158-4045-9714-69513ad56ab6]

________________________________

**Pull request closed without merging**
