### PR TITLE
Use of "Jube domne" also for Prime and Compline

### PR DESCRIPTION
**Pull request by FAJ-Munich**

### CODE REVIEW

**Comment by FAJ-Munich** [comment]
Dear @APMarcello3  and @fiapps 
I have found different translations for _Jube domne etc._ used in Prime and Compline compared to the one used in Matins for *French* and *Italian*. Please have a look and update `Prayers.txt` for these vernaculars if necessary. 

French:
```
[Jube domne]
V. Veuillez, Seigneur, bénir.
(sed rubrica 1960 dicitur)
V. Père, veuillez bénir.
```

Italian:
```
[Jube domne]
V. Dègnati, o padre, di benedirmi.
(sed rubrica 1960 dicitur)
V. Comanda o Signore, la benedizione.
```

**Comment by fiapps** [comment]
> Dear @APMarcello3 and @fiapps I have found different translations for _Jube domne etc._ used in Prime and Compline compared to the one used in Matins for _French_ and _Italian_. Please have a look and update `Prayers.txt` for these vernaculars if necessary.
> 
> French:
> 
> ```
> [Jube domne]
> V. Veuillez, Seigneur, bénir.
> (sed rubrica 1960 dicitur)
> V. Père, veuillez bénir.
> ```
> 
> Italian:
> 
> ```
> [Jube domne]
> V. Dègnati, o padre, di benedirmi.
> (sed rubrica 1960 dicitur)
> V. Comanda o Signore, la benedizione.
> ```

This is interesting: in French, it's "jube, Domine, benedicere" by default, but "jube, domne, benedicere" with the 1960 rubrics, whereas in Italian, it's the reverse. Looking at the Latin, it seems it's French that has it backwards. As for "comanda" vs. "dègnati", the latter corresponds to the consensus about the meaning of _jube,_ so I'll submit a PR making that consistent.

**Comment by FAJ-Munich** [comment]
The reverse order for French arises from the way I found the translations in the database. so far these have not been used to differentiate between pre- and post-1960 but one version came from Prime and the other from Matins. So, would the following be correct then?

```
[Jube domne]
V. Veuillez, père, bénir.
(sed rubrica 1960 dicitur)
V. Veuillez, Seigneur, bénir.
```

and 

```
[Jube domne]
V. Dègnati, o padre, di benedirmi.
(sed rubrica 1960 dicitur)
V. Dègnati, o Signore, di benedirmi.
```

**Comment by fiapps** [comment]
> The reverse order for French arises from the way I found the translations in the database. so far these have not been used to differentiate between pre- and post-1960 but one version came from Prime and the other from Matins. So, would the following be correct then?
> 
> ```
> [Jube domne]
> V. Veuillez, père, bénir.
> (sed rubrica 1960 dicitur)
> V. Veuillez, Seigneur, bénir.
> ```
> 
> and
> 
> ```
> [Jube domne]
> V. Dègnati, o padre, di benedirmi.
> (sed rubrica 1960 dicitur)
> V. Dègnati, o Signore, di benedirmi.
> ```

Yes, that would be correct (at least the Italian, and I think the French as well), though I was thinking of dropping "o" from both versions: it's not incorrect, but it's not the way people usually talk today.

**Pull request merged**
