### PR TITLE
Consistency of numbering of verses

### PR DESCRIPTION
**Pull request by efati**
* concerns Psalms 28 and 112
* Psalm 118: missing space in verse 2

### CODE REVIEW

**Comment by DLakomy** [comment]
I know it’s tempting to fix numbering, but it’s not that simple: look [here](https://github.com/DivinumOfficium/divinum-officium/pull/329).

**Comment by efati** [comment]
I see... :-|
But: I do not find any reference to parts of Psalm 28 or 112 in "Psalmi major.txt". It references whole psalms 28 and 112. It works for other languages.

**Comment by DLakomy** [comment]
Hmm... Seems legit.

I intended to check it, but have forgotten.

**Comment by DLakomy** [comment]
Many thanks.

**Comment by efati** [comment]
You are welcome!

**Pull request merged**
