### PR TITLE
Polish language version

### PR DESCRIPTION
**Pull request by mbab**
Taken from "Mszał Rzymski z dodaniem Nabożeństw Nieszpornych, o. Gaspar Lefebvre, Benedyktyn 1932" (Missale Romanum with Vespers).

Will try to keep completing through year - sundays and mayor sanctis.

### CODE REVIEW

**Comment by gregordick** [comment]
> Taken from "Mszał Rzymski z dodaniem Nabożeństw Nieszpornych, o. Gaspar Lefebvre, Benedyktyn 1932" (Missale Romanum with Vespers).

Could you please add this source to web/www/horas/Help/credits.html?

**Comment by mbab** [comment]
Source added

**Comment by gregordick** [comment]
Thanks very much.  Merged.

**Comment by mbab** [comment]
Great.

**Pull request merged**
