### PR TITLE
Code improvements / Kalendarium (esp. 1888) / Ranking of Days

### PR DESCRIPTION
**Pull request by FAJ-Munich**
This pull request contains a handful of code improvements and a lot of extras for the Transfer Tables according to the Tridentine rubrics and sometimes DA as well. 

PLEASE NOTE: I am not done with all the Transfer Tables yet, but I'd like to pull now since I might not have time to finish the remaing Transfer Tables for Dominical Letters A, b, c, and g until mid September! 

SECOND NOTE: Another major code improvement is necessary for the issue of Transferred Feasts superseding other feasts that still need to be commemorated. However, I have not yet fully understood how the code handles all the commemorations, so this is an open To Do which maybe also other people can contribute too. 

CONTENT:
1. **Adding Code Comments** to "getrank()" function making it more accessible for other contributers
2. **Kalendarium 1888**: Correction of Ranks of certain feasts and pegging certain other feasts to some particular Sundays (First Sunday of July, Sunday in the Octaves of Assumption and Nativity BMV, Third Sunday of September, First Sunday of October)
3. **Tridentine Rubrics**: Under these rubrics, every Duplex majus and every Duplex minus Doctoris Ecclesiæ also has the right to be transferred to another day not impeded by a day of nine lessons.
4. Implementing the "**Dynamic Dominica infra 8vam Epiphaniæ**", i.e., if January 6 and hence January 13 is a Sunday, then the office of the Sunday (including Holy Family) is anticipated to Saturday January 12.
In addition, according to the Tridentine Rubrics 1888, there are only 6 days of the Octave as the provided Scripture of the letter to the Romans always terminates before the Sunday. Hence, the days in the Octave need to be transfered by one day each for pre Divino rubrics depending on the Dominical Letter.
5. **Octaves and Ranking of days**:  The solutions to Issues [#3269](https://github.com/DivinumOfficium/divinum-officium/issues/3269) [#3284](https://github.com/DivinumOfficium/divinum-officium/issues/3284) and [#3288](https://github.com/DivinumOfficium/divinum-officium/issues/3288) concerning the ranking and labelling of Octaves is incomplete as, e.g., the CC Octave fails to outrank S. Barnabas Ap. in 2012 despite being an Octave of II. Order. This has been completed.
6. **Anticipated Vigils**: Renaming certain files such that the transferred() function in directorium.pm does not wrongly earmark days as transferred when they are actually not.

### CODE REVIEW

**Comment by FAJ-Munich** [comment]
Transfer tables for dominical letter "A" are also completed now; b, c, and g remain at the moment

**Comment by mbab** [comment]
Please squash some commits if You can, maybe based on mentioned points (use `git rebase -i` command().

**Comment by FAJ-Munich** [comment]
Does it make a difference in which order I squash? Latest to earliest or earliest to lates?

**Comment by mbab** [comment]
> Does it make a difference in which order I squash? Latest to earliest or earliest to lates?

You can change order of commits with mentioned command just by moving lines.
**Make new branch and experiment** (in end You will need make new pull request with new branch)

**Comment by mbab** [comment]
On other point, this branch has conflicts, do You have actual master? (`git rebase master`)

**Comment by FAJ-Munich** [comment]
Since I started with these developments back in May, in the mean time there have been developments in the master where I sorted out the conflicts by merging master frequently (12 commits as you can see) into my side branch; this is especially due to topic no. 5 the incomplete solution of the Octave day rankings and handling of the Corpus Christi octave. Hence, horascommon.pl has been quite a hassle to sort out the conflicts.
Are you saying that by rebasing, the conflicts would re-emerge?

**Pull request merged**
