### PR TITLE
Adding basic Polish translation of the Mass

### PR DESCRIPTION
**Pull request by mmolenda**
* Mass Ordinary - Rubrics 1960
* Prayers
* Prefaces - Common, Nativity, Holy Trinity
* Propers of four Advent Sundays

Reviewed by @DLakomy

### CODE REVIEW

**Comment by gregordick** [comment]
I would prefer that the vagrantfile and Apache config from fa6da86 not be pushed upstream.  I'm happy with the other commits, though.

**Comment by mmolenda** [comment]
Understood. I removed vagrantfile and Apache config.

**Comment by gregordick** [comment]
Thanks very much.

**Comment by mmolenda** [comment]
Thanks for merging. I'm happy I can contribute to venerable DivinumOfficium!

Cum Deo,
Marcin Molenda

2015-12-02 22:31 GMT+01:00 Gregor Dick <notifications@github.com>:

**Pull request merged**
