### PR TITLE
Fixing of Nocturn readings in Commune Doctorum

### PR DESCRIPTION
**Pull request by FAJ-Munich**
... and all the associated changes that come along in C4/a and C5/a and the corresponding Sancti as well.
Haven't checked the paschal tide files yet, tonight. This is to follow tomorrow.

@mbab Could you please run some tests if I have blundered something?

### CODE REVIEW

**Comment by FAJ-Munich** [comment]
I'll close the PR until confirmation by review. Thanks

**Comment by mbab** [comment]
Found following bad? changes in Trident+1910 Vesperas:
- 6-12/13-2026  commemorated ant. changed to "hic vir despiciens"
- 9/17/2025 Psalm 116 changed to 113

**Comment by FAJ-Munich** [comment]
God bless you for the quick review!

> Found following bad? changes in Trident+1910 Vesperas:
> 
>     * 6-12/13-2026  commemorated ant. changed to "hic vir despiciens"
This one is intentional. Antonius has been declared a Doctor of the Church in 1946 only.

> 
>     * 9/17/2025 Psalm 116 changed to 113
Thanks for pointing that out. I had fixed this issue with the "AnteCapitulum" on my other branch already and forgot to cherry-pick that over to master. should be fixed now by fd2015ff469ab87d5f7a611ceba58270da18caf8

W.r.t. the 5th Psalm in Vespers I came across this weird condition in `psalmi.pl` line 443 after my changes:
```
&& ($vespera == 3 || ($rank < 6 && $dayofweek == 5))    # TO DO: What is tried to capture on a Friday night?
```
So on a Friday night, the second condition gives a true when we are in first Vespers of whatever Feast is said on Saturday. Then, the algorith uses the 5th Psalm for Second Vespers instead of First Vespers. Do you @mbab have an idea what case could be addressed here? If it was for Rubrics 1960 it doesn't make sense as nothing below the rank of I. class has first vespers anyways. If it is about the fact that Second Vespers of the Feast is usually loosing in concurrence with the Sunday, I don't think the condition is correct as it stands since the latter is not always true even after Divino Afflatu. I'm puzzled.

Last but not least, I have rebased my `master` and force pushed the updates to capture also Paschal Tide now. Maybe you could give it a final check again. Thank you so much.

+LJCh+

**Comment by mbab** [comment]
> W.r.t. the 5th Psalm in Vespers I came across this weird condition in `psalmi.pl` line 443 after my changes:
> 
> ```
> && ($vespera == 3 || ($rank < 6 && $dayofweek == 5))    # TO DO: What is tried to capture on a Friday night?
> ```

Removing second part of alternative sets proper last psalm in Tridents for 1-{12,19,26}-2024, no other versions are affected.

> Last but not least, I have rebased my `master` and force pushed the updates to capture also Paschal Tide now. Maybe you could give it a final check again. Thank you so much.

Actually I lost - in unknown circumstances, it just disappear - directory with my test tools. It will took me some time to rebuild.

+

**Comment by FAJ-Munich** [comment]
Thanks for checking. Especially the case of 1-19-2024 tells me that this condition is just wrong. It simply makes no sense and their is not rubric in Tridentine books that imply such.

> Actually I lost - in unknown circumstances, it just disappear - directory with my test tools. It will took me some time to rebuild.

Oh no! Good luck with that. I have run more checks myself today so I am comfortable to reopen the PR _(albeit separetly since the force push forbids reopening this one.)_

**Pull request closed without merging**
