### PR TITLE
Spanish translation and English simplification using @ references.

### PR DESCRIPTION
**Pull request by d4h0y0sr**

### CODE REVIEW

**Comment by FAJ-Munich** [comment]
@d4h0y0sr  
As I see you are not making use of the inheritance of @ references: in most cases, these can go into the Latin and then they are not necessary in the English anymore as well. Of course, if Latin has the reference but English has the text, then the @ reference is not inherited to the other vernaculars like Spanish anymore. So maybe you can simplify even better by checking the Latin as well first. 

+Laudetur Jesus Christus+

**Comment by FAJ-Munich** [comment]
"Now making use of" — sorry for the wrong autocorrect

**Comment by d4h0y0sr** [comment]
Oh ok Thanks for the aclaration

**Comment by APMarcello3** [comment]
@d4h0y0sr Please also be aware of issue #525 when simplifying texts.

**Pull request merged**
