### PR TITLE
Latin files changes

### PR DESCRIPTION
**Pull request by mbab**
+AMDG+

### CODE REVIEW

**Comment by gregordick** [comment]
The Tridentine Latin files are not quite identical to the post-Tridentine versions: often the Matins lessons are arranged differently or are longer in the Tridentine breviary.  I've only checked Quad2-0 from this patch, but in general this tends to be the case.  Could you please review that commit?

**Comment by mbab** [comment]
Yes there are differences which in fact are mistakes:

- Quad2-0. Lectio 4 in books ends with: *possit ista ratione mendacium nuncupari.*
Following: *Cum enim dicimus fluctuare..* is not present.
- Quad3-4 and Quad4-2: Last sentence in Lectio 1 is duplicated first sentence of Lection 2.
- Quad6-0: Same as above in Lectio 7 (and 8).

All other files are same apart punctation and typos.

**Comment by mbab** [comment]
I would like to know status of this PR, is it acceptable or should I close them?
Resolving conflits is not hard:
1. remove files
```
web/www/horas/Latin/Tempora/Quad2-0t.txt
web/www/horas/Latin/Tempora/Quad5-0t.txt
```
2. in file Tr1570 replace all `Quad` lines with only two:
```
Tempora/Quad4-0=Tempora/Quad4-0t;;                                                                                                                                            
Tempora/Quad5-5=Tempora/Quad5-5Feriat;;
```

**Comment by gregordick** [comment]
If you're certain that the changes to the Tridentine files bring them into conformance with the 1568 books, then I'm happy to fix up the conflicts and merge.

**Comment by mbab** [comment]
I can't be sure as I have no access to such books.
I reverted changes in Quad2-0t. (Maybe someone with access to books can check Lectio4.)
Files: Quad3-4 and Quad4-2, I can't believe puting same line in two lectios can be no mistake.
All other *files* are same apart punctiations and typos.

**Comment by APMarcello3** [comment]
mbab, could you kindly resolve these conflicts so that I can merge and close this pull? Thank you.

**Pull request closed without merging**
