### PR TITLE
Abbreviations of books 

### PR DESCRIPTION
**Pull request by luc--**
Hello !

This pull request changes all abbreviations of the Bible books used in both directories hora and missa.
A script is provided in the admin directory (with some POD format documentation).

(issue #582)

### CODE REVIEW

**Comment by LGD-Fr** [comment]
@luc--,i seems your script missed the books with numbers (1 Reg, 2 Cor etc.)
I wrote a shell script to correct this. (20dc390)

**Comment by LGD-Fr** [comment]
I fixed the bash script (5c9a4a2), so now latine abbreviations are used also for numbered books (1 Reg etc.)

**Comment by fiapps** [comment]
Personally, I don't see why it is desirable to use the Latin abbreviations in other languages, which are offered as translations of the Latin. Why translate the text and not the abbreviation? Anyone who wants the Latin abbreviation can see it in the Latin column next to the translation. On the other hand those who are viewing a translation are presumably doing so because they are not fluent in Latin, and may therefore not recognize the Latin abbreviations.

Nevertheless, I leave it to @APMarcello3 to decide what to do for the English translation.

**Comment by luc--** [comment]
Hello, I’ve made an answer in the issue #582.

**Pull request merged**
