### PR TITLE
Mass - Adds a French translation of the Ordo

### PR DESCRIPTION
**Pull request by LGD-Fr**
Why "French" and not "français" ? Because it did not work with "français"… Maybe the "ç" ?

### CODE REVIEW

**Comment by gregordick** [comment]
Thanks very much: looks excellent.  Before I merge, could you please add any sources used for the translation to `web/www/horas/Help/credits.html`?

UTF-8 in paths is probably not handled correctly, hence the problem with 'français'.  I'll open a bug to track the implementation of a fix for this.

**Comment by LGD-Fr** [comment]
I also must check the permissions and intellectual properties, I pulled request too early.

**Comment by LGD-Fr** [comment]
The credits are now updated @gregordick ; we also added some translations of the propers.

**Comment by gregordick** [comment]
Merged.  Thanks very much!

**Pull request merged**
